deploy moved back

diff --git a/gitlab-ci-template.yml b/gitlab-ci-template.yml
--- a/gitlab-ci-template.yml
+++ b/gitlab-ci-template.yml
@@ -62,6 +62,7 @@ staging:
   services:
   - docker:stable-dind
   script:
+  - prepare_deploy
   - deploy
   environment:
     name: staging
@@ -78,6 +79,7 @@ production:
   when: manual
   allow_failure: false
   script:
+  - prepare_deploy
   - deploy
   environment:
     name: production
@@ -111,6 +113,51 @@ production:
     docker push "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG"
   }
 
+  function prepare_deploy() {
+
+    echo "Installing dependencies..."
+
+    apk add -U openssl curl tar gzip bash ca-certificates git
+    curl -L -o /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
+    curl -L -O https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
+    apk add glibc-2.28-r0.apk
+    rm glibc-2.28-r0.apk
+
+    curl "https://kubernetes-helm.storage.googleapis.com/helm-v${HELM_VERSION}-linux-amd64.tar.gz" | tar zx
+    mv linux-amd64/helm /usr/bin/
+    mv linux-amd64/tiller /usr/bin/
+    helm version --client
+    tiller -version
+
+    curl -L -o /usr/bin/kubectl "https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl"
+    chmod +x /usr/bin/kubectl
+    kubectl version --client
+
+    echo "Checking kubernetes namespace..."
+
+    kubectl describe namespace "$KUBE_NAMESPACE" || kubectl create namespace "$KUBE_NAMESPACE"
+
+    echo "Initializing Tiller..."
+
+    export HELM_HOST="localhost:44134"
+    tiller -listen ${HELM_HOST} -alsologtostderr > /dev/null 2>&1 &
+
+    if ! helm version --debug; then
+      echo "Failed to init Tiller."
+      return 1
+    fi
+
+    echo "Creating secret..."
+
+    kubectl create secret -n "$KUBE_NAMESPACE" \
+      docker-registry gitlab-registry \
+      --docker-server="$CI_REGISTRY" \
+      --docker-username="${CI_DEPLOY_USER:-$CI_REGISTRY_USER}" \
+      --docker-password="${CI_DEPLOY_PASSWORD:-$CI_REGISTRY_PASSWORD}" \
+      --docker-email="$GITLAB_USER_EMAIL" \
+      -o yaml --dry-run | kubectl replace -n "$KUBE_NAMESPACE" --force -f -
+  }
+
   function deploy() {
     export DOCKER_HOST='tcp://localhost:2375'
     docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
@@ -118,7 +165,18 @@ production:
     docker tag "$CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG" "$CI_APPLICATION_REPOSITORY:$CI_ENVIRONMENT_SLUG"
     docker push "$CI_APPLICATION_REPOSITORY:$CI_ENVIRONMENT_SLUG"
 
-    echo "TODO: Now deployment pipeline should be triggered..."
+    git clone $CHART_REPO_URL
+
+    helm delete --purge ${APP_NAME}-${CI_ENVIRONMENT_SLUG}
+
+    helm upgrade --install \
+    --debug \
+    --wait \
+    --namespace="$KUBE_NAMESPACE" \
+    --tiller-namespace="$TILLER_NAMESPACE" \
+    -f values-${CI_ENVIRONMENT_SLUG}.yaml \
+    "${APP_NAME}-${CI_ENVIRONMENT_SLUG}" \
+    ${CHART_REPO_NAME}/
   }
 
 before_script:
